test_1a_register (__main__.GSChrome) ... skipped 'Logged in'
test_1b_login (__main__.GSChrome) ... skipped 'Logged in'
test_2a_mount_container (__main__.GSChrome) ... ok
test_2b_disconnect_container (__main__.GSChrome) ... ok
test_3_setting_up (__main__.GSChrome) ... ok
test_4a_import_url (__main__.GSChrome) ... ok
test_4b_upload_file (__main__.GSChrome) ... ok
test_5a_generate_public_URL (__main__.GSChrome) ... ok
test_6a_change_file_name (__main__.GSChrome) ... ERROR
test_6b_copy_data_btw_folders (__main__.GSChrome) ... ok
test_6c_copy_data_btw_containers (__main__.GSChrome) ... ERROR
test_6d_delete_file (__main__.GSChrome) ... ok
test_6e_move_data_btw_folders (__main__.GSChrome) ... ERROR
test_6f_move_data_btw_containers (__main__.GSChrome) ... ERROR
test_7b_launch_with_file (__main__.GSChrome) ... ok
test_8_get_DOI (__main__.GSChrome) ... ERROR

======================================================================
ERROR: test_6a_change_file_name (__main__.GSChrome)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Regina/Documents/VLSCI_MAC_Documents/UROP/SeleniumTesting/data_manipulation.py", line 58, in test_6a_change_file_name
    raise RenameException("Failed to rename the file: " + response)
RenameException: Failed to rename the file: Failure: 500  Response: <html><head><title>Apache Tomcat/7.0.26 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 500 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The server encountered an internal error () that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>java.lang.NullPointerException
</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.26 logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.26</h3></body></html>

======================================================================
ERROR: test_6c_copy_data_btw_containers (__main__.GSChrome)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Regina/Documents/VLSCI_MAC_Documents/UROP/SeleniumTesting/data_manipulation.py", line 134, in test_6c_copy_data_btw_containers
    raise CopyException("Failed to copy the file between containers. \n" + response)
CopyException: Failed to copy the file between containers. 
Failure: 500  Response: <html><head><title>Apache Tomcat/7.0.26 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 500 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The server encountered an internal error () that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>java.lang.NullPointerException
</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.26 logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.26</h3></body></html>

======================================================================
ERROR: test_6e_move_data_btw_folders (__main__.GSChrome)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Regina/Documents/VLSCI_MAC_Documents/UROP/SeleniumTesting/data_manipulation.py", line 186, in test_6e_move_data_btw_folders
    raise MoveException("Failed to move the data between folders. \n" + response)
MoveException: Failed to move the data between folders. 
Failure: 500  Response: <html><head><title>Apache Tomcat/7.0.26 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 500 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The server encountered an internal error () that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>java.lang.NullPointerException
</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.26 logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.26</h3></body></html>

======================================================================
ERROR: test_6f_move_data_btw_containers (__main__.GSChrome)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Regina/Documents/VLSCI_MAC_Documents/UROP/SeleniumTesting/data_manipulation.py", line 211, in test_6f_move_data_btw_containers
    raise MoveException("Failed to move the data between containers. \n" + response)
MoveException: Failed to move the data between containers. 
Failure: 500  Response: <html><head><title>Apache Tomcat/7.0.26 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 500 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The server encountered an internal error () that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>java.lang.NullPointerException
</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.26 logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.26</h3></body></html>

======================================================================
ERROR: test_8_get_DOI (__main__.GSChrome)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Regina/Documents/VLSCI_MAC_Documents/UROP/SeleniumTesting/file_publish.py", line 41, in test_8_get_DOI
    raise Exception("Failed to get DOI of the file." + response)
Exception: Failed to get DOI of the file.Failure: 404  Response: Could not find the path

----------------------------------------------------------------------
Ran 16 tests in 416.592s

FAILED (errors=5, skipped=2)
